import { describe, test, expect } from 'bun:test';
import { extractMethods, generateSource } from './codegen-bridge';

describe('extractMethods', () => {
  test('extracts method names from registerHandler calls', () => {
    const zig = `
    try bridge.registerHandler("shell.open", handleOpen);
    try bridge.registerHandler("fs.readText", handleRead);
    `;
    expect(extractMethods(zig)).toEqual(['shell.open', 'fs.readText']);
  });

  test('ignores addHandler (private) and comments', () => {
    const zig = `
    // registerHandler("ignored.comment", foo)
    try bridge.addHandler("also.ignored", foo);
    `;
    expect(extractMethods(zig)).toEqual([]);
  });

  test('returns empty array for source with no handlers', () => {
    expect(extractMethods('const x: usize = 5;')).toEqual([]);
  });
});

describe('generateSource', () => {
  test('emits sorted deduplicated union type with header comment', () => {
    const out = generateSource(['shell.open', 'alert.show', 'shell.open']);
    expect(out).toContain('// Auto-generated by tools/codegen-bridge.ts');
    expect(out).toContain('export type MethodName =');
    expect(out).toContain('  | "alert.show"');
    expect(out).toContain('  | "shell.open"');
    // sorted: alert before shell
    expect(out.indexOf('"alert')).toBeLessThan(out.indexOf('"shell'));
    // deduplicated: "shell.open" appears exactly once
    expect((out.match(/"shell\.open"/g) ?? []).length).toBe(1);
  });

  test('single method produces valid union syntax', () => {
    const out = generateSource(['ping']);
    expect(out).toContain('  | "ping"');
  });

  test('empty methods array emits never type', () => {
    const out = generateSource([]);
    expect(out).toContain('export type MethodName = never;');
    expect(out).toContain('// Auto-generated by tools/codegen-bridge.ts');
  });
});
