import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { join, resolve } from 'path';

const REGISTER_RE = /\.registerHandler\("([^"]+)"/g;

/** Extract all method names from one Zig source string. */
export function extractMethods(zigSource: string): string[] {
  const methods: string[] = [];
  for (const match of zigSource.matchAll(REGISTER_RE)) {
    methods.push(match[1]);
  }
  return methods;
}

/** Emit a TypeScript source string with a MethodName union. */
export function generateSource(methods: string[]): string {
  const sorted = [...new Set(methods)].sort();
  const header = '// Auto-generated by tools/codegen-bridge.ts — do not edit.';
  if (sorted.length === 0) {
    return `${header}\nexport type MethodName = never;\n`;
  }
  const union = sorted.map(m => `  | "${m}"`).join('\n');
  return [header, 'export type MethodName =', union + ';', ''].join('\n');
}

function parseArgs(argv: string[]): { srcDir: string; outFile: string } {
  const args = argv.slice(2);
  const srcIdx = args.indexOf('--src');
  const outIdx = args.indexOf('--out');
  return {
    srcDir: srcIdx >= 0 ? args[srcIdx + 1] : resolve(import.meta.dir, '../src'),
    outFile: outIdx >= 0 ? args[outIdx + 1] : resolve(import.meta.dir, '../bridge-js/src/generated.ts'),
  };
}

function main() {
  const { srcDir, outFile } = parseArgs(process.argv);
  // bridge.zig is infrastructure; its registerHandler calls are test-only stubs.
  const zigFiles = readdirSync(srcDir).filter(f => f.endsWith('.zig') && f !== 'bridge.zig');
  const allMethods: string[] = [];

  for (const file of zigFiles) {
    const content = readFileSync(join(srcDir, file), 'utf-8');
    allMethods.push(...extractMethods(content));
  }

  const source = generateSource(allMethods);
  writeFileSync(outFile, source, 'utf-8');

  const count = new Set(allMethods).size;
  console.log(`Generated ${count} methods → ${outFile}`);
}

// Guard: only run filesystem I/O when executed directly, not when imported by tests.
if (import.meta.main) {
  main();
}
