//! Runnable example for the wkz library.
//!
//! Responsibility: the smallest program that opens a window with a WKWebView,
//! exercising the public wkz API end-to-end. This is what `zig build run`
//! launches. It boots the NSApplication, creates a centered window, fills its
//! contentView with a WKWebView, loads content (Vite dev server in dev mode;
//! embedded `dist/` assets via `app://local` in prod), foregrounds the app,
//! and enters the run loop. Main thread only.
//!
//! Asset routing:
//!   -Ddev=true  → loadURL("http://localhost:5173")  — Vite dev server
//!   -Ddev=false → initWithSchemeHandler + loadURL("app://local/index.html")
//!                 serving @embedFile'd assets from the `dist_assets` module.

const std = @import("std");
const objc = @import("objc");
const wkz = @import("wkz");
const build_options = @import("build_options");
// `dist_assets` is always present: in dev mode it is a stub empty AssetMap;
// in prod it is generated by tools/gen_assets.zig from frontend/dist/.
// Keeping the import unconditional lets the compiler verify it in both modes.
const dist_assets = @import("dist_assets");

pub fn main() !void {
    std.log.info("wkz example — dev mode: {}", .{build_options.dev});

    // Allocator for Bridge (JSON parsing, dispatch table, JS string building).
    // std.heap.GeneralPurposeAllocator was renamed to std.heap.DebugAllocator in
    // Zig 0.16 (heap.zig:20). Lives for the entire process lifetime.
    // NOTE: `defer _ = gpa.deinit()` is intentionally dead code — app.run() below
    // blocks until AppKit's `terminate:` exits the process directly, so the defer
    // can never fire. It is written for clarity (leak detection in a hypothetical
    // early-return path) and the OS reclaims memory on exit.
    var gpa = std.heap.DebugAllocator(.{}).init;
    defer _ = gpa.deinit();

    // Order matters: the shared NSApplication must exist before any window is
    // created, so App.init() runs first.
    var app = try wkz.app.App.init();

    // Centered, titled/closable/resizable window. It must outlive the run loop;
    // see the lifetime note on `run()` below for why no deinit is called.
    const window = try wkz.window.Window.init(900, 600, "wkz");

    // Prod: build a SchemeHandler backed by the embedded asset map and create the
    // WKWebView with the scheme pre-registered on its configuration.
    //
    // Dev: create a plain WKWebView (no scheme handler needed; Vite serves assets).
    //
    // The WebView is not attached to any window yet — call `attach` to add it to
    // a window's contentView.
    //
    // Ownership note: `scheme_handler` is intentionally never deinit'd.
    // `app.run()` blocks below and `terminate:` exits the process directly, so
    // any defers after `run()` are dead code. The OS reclaims memory on exit.
    const webview = if (build_options.dev) blk: {
        break :blk try wkz.webview.WebView.init();
    } else blk: {
        // SchemeHandler.init borrows the AssetMap pointer — the map must outlive
        // the handler. `dist_assets.asset_map` is a comptime constant with static
        // lifetime, so this is always satisfied.
        var scheme_handler = try wkz.scheme.SchemeHandler.init(&dist_assets.asset_map);
        // initWithSchemeHandler registers the handler on the WKWebViewConfiguration
        // before the WKWebView is created; WebKit freezes configuration afterwards.
        break :blk try wkz.webview.WebView.initWithSchemeHandler(scheme_handler.object(), "app");
    };
    webview.attach(window);

    // Bridge must be fully wired BEFORE content is loaded: addScriptMessageHandler
    // only takes effect for content loaded after the call (WebKit requirement).
    //
    // Bridge.init takes the raw WKWebView objc.Object (webview.ns_webview) so it
    // can call evaluateJavaScript:completionHandler: for replies. The
    // WKUserContentController comes from webview.userContentController().
    //
    // init() returns a by-value Bridge; we then place it at a stable address
    // (the local `bridge`) and call attach(*Bridge) to write that address into
    // the handler's ivar. The IMP will recover this pointer on every message.
    //
    // NOTE: `bridge.deinit()` is intentionally omitted — app.run() blocks; the
    // process exits via terminate: and the OS reclaims everything. Installing a
    // defer here would be dead code identical to the webview/window situation.
    var bridge = try wkz.bridge.Bridge.init(
        gpa.allocator(),
        webview.userContentController(),
        webview.ns_webview,
    );
    try bridge.attach();

    // Demo "ping" → "pong" round-trip. The frontend calls:
    //   invoke("ping", {})  ->  JS postMessage({method:"ping",id:N})
    // The bridge dispatches here, and resolve(id, `"pong"`) evaluates:
    //   __resolve(N, "pong")
    // in the webview, completing the promise on the JS side.
    try bridge.registerHandler("ping", struct {
        fn handle(b: *wkz.bridge.Bridge, _: std.json.Value, id: ?i64) void {
            if (id) |i| b.resolve(i, "\"pong\"") catch {};
        }
    }.handle);

    // Load content: Vite dev server in dev mode, embedded assets in prod.
    if (build_options.dev) {
        // Dev mode: load the Vite dev server. Requires NSAllowsLocalNetworking=YES
        // in Info.plist when running as a sandboxed .app bundle (M4). Under
        // `zig build run` (no sandbox), the connection works without it.
        try webview.loadURL("http://localhost:5173");
    } else {
        // Prod mode: serve embedded assets via the app:// custom scheme.
        // The scheme handler (registered above) resolves "app://local/..." to
        // entries in dist_assets.asset_map.
        try webview.loadURL("app://local/index.html");
    }

    // Foreground the app, then enter the AppKit run loop. `run()` blocks until
    // the user quits (Cmd+Q -> `terminate:`), and AppKit's `terminate:` exits
    // the process directly — it does NOT return control to Zig. Therefore no
    // `defer window.deinit()` / `defer webview.deinit()` / `defer bridge.deinit()`
    // is installed: such defers would be dead code (they could never fire), and
    // the OS reclaims the process's memory on exit.
    app.activate();
    app.run();
}

test {
    std.testing.refAllDecls(@This());
}
