// Auto-generated by tools/codegen-bridge.ts — do not edit.
export type MethodName =
  | "alert.show"
  | "clipboard.readText"
  | "clipboard.writeText"
  | "fs.openFile"
  | "fs.readBinary"
  | "fs.readText"
  | "fs.savePanel"
  | "fs.writeBinary"
  | "fs.writeText"
  | "notifications.requestPermission"
  | "notifications.send"
  | "shell.open"
  | "statusitem.remove"
  | "statusitem.set"
  | "updater.check"
  | "updater.download"
  | "updater.install";
